# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_UserEditorWindow(object):

    def setupUi(self, UserEditorWindow):
        UserEditorWindow.setObjectName("UserEditorWindow")
        UserEditorWindow.resize(350, 338)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHeightForWidth(UserEditorWindow.sizePolicy().hasHeightForWidth())
        UserEditorWindow.setSizePolicy(sizePolicy)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(UserEditorWindow)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.mainFrame = QtWidgets.QFrame(UserEditorWindow)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # profile list
        self.profileListFrame = QtWidgets.QFrame(self.mainFrame)
        self.profileListFrame.setSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        self.profileListFrame.setMaximumSize(QtCore.QSize(360, 16777215))
        self.profileListFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profileListFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profileListFrame.setObjectName("profileListFrame")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.profileListFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.userLabel = QtWidgets.QLabel(self.profileListFrame)
        self.userLabel.setObjectName("userLabel")
        self.verticalLayout_2.addWidget(self.userLabel)

        self.userListWidget = QtWidgets.QListWidget(self.profileListFrame)
        self.userListWidget.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.userListWidget.setObjectName("userListWidget")
        self.verticalLayout_2.addWidget(self.userListWidget)

        self.horizontalLayout.addWidget(self.profileListFrame)

        # Button frame
        self.buttonDoubleFrame = QtWidgets.QFrame(self.mainFrame)
        self.buttonDoubleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonDoubleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonDoubleFrame.setObjectName("buttonDoubleFrame")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.buttonDoubleFrame)
        self.verticalLayout_3.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.buttonFrame = QtWidgets.QFrame(self.buttonDoubleFrame)
        self.buttonFrame.setMinimumSize(QtCore.QSize(91, 181))
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttonFrame)
        self.verticalLayout.setObjectName("verticalLayout")

        self.addUserButton = QtWidgets.QPushButton(self.buttonFrame)
        self.addUserButton.setMinimumSize(QtCore.QSize(71, 21))
        self.addUserButton.setMaximumSize(QtCore.QSize(16777215, 48))
        self.addUserButton.setObjectName("addUserButton")
        self.verticalLayout.addWidget(self.addUserButton)

        self.editUserButton = QtWidgets.QPushButton(self.buttonFrame)
        self.editUserButton.setEnabled(False)
        self.editUserButton.setMinimumSize(QtCore.QSize(71, 21))
        self.editUserButton.setMaximumSize(QtCore.QSize(16777215, 48))
        self.editUserButton.setObjectName("editUserButton")
        self.verticalLayout.addWidget(self.editUserButton)

        self.deleteUserButton = QtWidgets.QPushButton(self.buttonFrame)
        self.deleteUserButton.setEnabled(False)
        self.deleteUserButton.setMinimumSize(QtCore.QSize(71, 21))
        self.deleteUserButton.setMaximumSize(QtCore.QSize(16777215, 48))
        self.deleteUserButton.setObjectName("deleteUserButton")
        self.verticalLayout.addWidget(self.deleteUserButton)

        self.testUserButton = QtWidgets.QPushButton(self.buttonFrame)
        self.testUserButton.setEnabled(False)
        self.testUserButton.setMinimumSize(QtCore.QSize(71, 21))
        self.testUserButton.setMaximumSize(QtCore.QSize(16777215, 48))
        self.testUserButton.setObjectName("testUserButton")
        self.verticalLayout.addWidget(self.testUserButton)

        self.cancelUserButton = QtWidgets.QPushButton(self.buttonFrame)
        self.cancelUserButton.setMinimumSize(QtCore.QSize(71, 21))
        self.cancelUserButton.setMaximumSize(QtCore.QSize(16777215, 48))
        self.cancelUserButton.setObjectName("cancelUserButton")
        self.verticalLayout.addWidget(self.cancelUserButton)

        spacerItem = QtWidgets.QSpacerItem(20, 375, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.signInButton = QtWidgets.QPushButton(self.buttonFrame)
        self.signInButton.setEnabled(False)
        self.signInButton.setMaximumSize(QtCore.QSize(16777215, 48))
        self.signInButton.setObjectName("signInButton")
        self.verticalLayout.addWidget(self.signInButton)

        self.verticalLayout_3.addWidget(self.buttonFrame)
        self.horizontalLayout.addWidget(self.buttonDoubleFrame)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout_2.addWidget(self.mainFrame)

        self.retranslateUi(UserEditorWindow)
        QtCore.QMetaObject.connectSlotsByName(UserEditorWindow)
        
    def retranslateUi(self, UserEditorWindow):
        _translate = QtCore.QCoreApplication.translate
        UserEditorWindow.setWindowTitle(_translate("UserEditorWindow", "Edit Profiles"))
        self.userLabel.setText(_translate("UserEditorWindow", "Profiles:"))
        self.addUserButton.setText(_translate("UserEditorWindow", "Add"))
        self.editUserButton.setText(_translate("UserEditorWindow", "Edit"))
        self.deleteUserButton.setText(_translate("UserEditorWindow", "Delete"))
        self.testUserButton.setText(_translate("UserEditorWindow", "Test"))
        self.cancelUserButton.setText(_translate("UserEditorWindow", "Cancel"))
        self.signInButton.setText(_translate("UserEditorWindow", "Sign in"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserEditorWindow = QtWidgets.QWidget()
    ui = Ui_UserEditorWindow()
    ui.setupUi(UserEditorWindow)
    UserEditorWindow.show()
    sys.exit(app.exec_())
